-- ─────────────────────────────────────────────────────────────────────────────
-- fix_column_types.sql
-- Run ONCE in Snowflake to convert FLOAT/NUMBER columns to BIGINT.
-- Power BI maps BIGINT → Whole Number, NUMBER → Decimal Number.
-- After running this, trigger dbt run to recreate mart tables with BIGINT types.
-- ─────────────────────────────────────────────────────────────────────────────

USE DATABASE GITHUB_PIPELINE;
USE SCHEMA RAW;

-- Fix numeric columns in RAW table
ALTER TABLE RAW_GITHUB_EVENTS ALTER COLUMN STARS         SET DATA TYPE BIGINT;
ALTER TABLE RAW_GITHUB_EVENTS ALTER COLUMN FORKS         SET DATA TYPE BIGINT;
ALTER TABLE RAW_GITHUB_EVENTS ALTER COLUMN OPEN_ISSUES   SET DATA TYPE BIGINT;
ALTER TABLE RAW_GITHUB_EVENTS ALTER COLUMN COMMIT_COUNT  SET DATA TYPE BIGINT;
ALTER TABLE RAW_GITHUB_EVENTS ALTER COLUMN PR_NUMBER     SET DATA TYPE BIGINT;
ALTER TABLE RAW_GITHUB_EVENTS ALTER COLUMN ISSUE_NUMBER  SET DATA TYPE BIGINT;

-- Verify
SELECT COLUMN_NAME, DATA_TYPE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'RAW'
  AND TABLE_NAME   = 'RAW_GITHUB_EVENTS'
  AND COLUMN_NAME IN ('STARS','FORKS','OPEN_ISSUES','COMMIT_COUNT','PR_NUMBER','ISSUE_NUMBER');
